import { Montserrat } from "next/font/google";
import "./globals.css";
import GlobalProvider from "./context/Globalcontext";
import Navbar from "./components/Navbar";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </GlobalProvider>
    </html>
  );
}
